// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyrXbdUB4g0n00BIrunH9Z1bvtupFROIs',
    appId: '1:658257497144:web:5d497633193191eaffeacd',
    messagingSenderId: '658257497144',
    projectId: 'sample-here',
    authDomain: 'sample-here.firebaseapp.com',
    storageBucket: 'sample-here.appspot.com',
    measurementId: 'G-K5VEHZRYBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYYJkX6xQgyUrpGH6qeUkmkTaNKMX3CxA',
    appId: '1:658257497144:android:9116cf71bff7ba6affeacd',
    messagingSenderId: '658257497144',
    projectId: 'sample-here',
    storageBucket: 'sample-here.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWMQ3oNQZwoGl5KOE5aA9pnFhHMhL1c0A',
    appId: '1:658257497144:ios:136647ec56364909ffeacd',
    messagingSenderId: '658257497144',
    projectId: 'sample-here',
    storageBucket: 'sample-here.appspot.com',
    iosClientId: '658257497144-bc7i4f0lufc80d31f3q9ban3noptb7lb.apps.googleusercontent.com',
    iosBundleId: 'com.sopln.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWMQ3oNQZwoGl5KOE5aA9pnFhHMhL1c0A',
    appId: '1:658257497144:ios:136647ec56364909ffeacd',
    messagingSenderId: '658257497144',
    projectId: 'sample-here',
    storageBucket: 'sample-here.appspot.com',
    iosClientId: '658257497144-bc7i4f0lufc80d31f3q9ban3noptb7lb.apps.googleusercontent.com',
    iosBundleId: 'com.sopln.sample',
  );
}
